services:
  backend:
    build: .
    command: python3 dongi/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A dongi worker --loglevel=info
    volumes:
      - ./dongi:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env.dev
    user: myuser

  flower:
    build: ./
    command: celery -A dongi flower --broker=redis://redis:6379/0
    volumes:
      - ./dongi:/app
    ports:
      - 5555:5555
    env_file:
      - .env.dev
    depends_on:
      - celery
      - redis

  locust:
    image: locustio/locust
    volumes:
      - ./dongi:/mnt
    command: -f /mnt/locustfile.py --host=http://backend:8000
    ports:
      - "8089:8089"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dongi/static:/usr/share/nginx/html/static/backend



volumes:
  postgres_data:
