# Generated by Django 5.1.5 on 2025-03-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='dongi/expense/receipts/'),
        ),
    ]
