# Generated by Django 5.1.5 on 2025-02-19 05:25

import django_ulid.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=django_ulid.models.ULIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expenseshare',
            name='id',
            field=django_ulid.models.ULIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=django_ulid.models.ULIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
